Repository fanzip/fanzip-client, pull requests merged in 2025-08, with the labels that each got.

#38 [feat] 예약 페이지 구현
  src/App.vue
  src/assets/icons/KBPay.svg
  src/assets/icons/KakaoPay.svg
  src/assets/icons/TossPay.svg
  src/assets/icons/poster.svg
  src/assets/icons/yeodano.svg
  src/components/common/ButtonNav.vue
  src/components/common/PaymentMethodSelector.vue
  src/components/common/SearchBar.vue
  src/components/layout/AppHeader.vue
  src/data/fanMeetingData.js
  src/pages/FanMeetingDetailPage.vue
  src/pages/FanMeetingPage.vue
  src/pages/FanMeetingPaymentPage.vue
  src/pages/HomePage.vue
  src/pages/PaymentCompletePage.vue
  src/pages/PaymentSuccessPage.vue
  src/pages/SeatSelectPage.vue
  src/pages/reservation/FanMeetingDetailPage.vue
  src/pages/reservation/FanMeetingPage.vue
  src/pages/reservation/FanMeetingPaymentPage.vue
  src/pages/reservation/SeatSelectPage.vue
  src/router/fanMeeting.js
  src/router/index.js
  src/router/reservation.js
Labels: 경한

#114 [feat] 팬카드 상세 페이지 기능 개선 - 구독 취소 및 추억 기능
  src/api/membershipApi.js
  src/pages/fancard/FanCardDetailPage.vue
  src/pages/fancard/FanCardPage.vue
  vite.config.js
Labels: 경한

#120 [fix] 배지 안보이던 문제 해결
  src/components/fanCard/FanCardList.vue
  src/pages/fancard/FanCardDetailPage.vue
  src/pages/fancard/FanCardPage.vue
Labels: 경한

#125 [feat] 팬 카드 페이지 비활성 상태 추가 및 추억 탭 수정
  src/pages/fancard/FanCardDetailPage.vue
  src/pages/fancard/FanCardPage.vue
Labels: 경한

#137 [fix] 좌석 더미 데이터 제거
  src/pages/reservation/SeatSelectPage.vue
Labels: 경한

#144 [bugfix] 라우터 경로 수정
  src/pages/auth/LoginPage.vue
Labels: enhancement, 승원

#147 [refactor] 원래 코드로 수정
  src/api/newReviewApi.js
  src/api/reviewAdminApi.js
  src/pages/NewAdminPage.vue
  src/pages/auth/LoginPage.vue
  src/router/index.js
Labels: 승원
